### ISSUE TITLE
doesn't allow float inputs, and float output is converted to double

### ISSUE THREAD

**Issue by ahbarnett** [zgimbutas/mwrap#2]
Dear Zydrunas,
I'm trying to use mwrap for floats (interface to single prec FINUFFT),
but I'm getting problems traced to mwrap. The manual implies float is a standard type. Yet when I compile C funcs with floats, it fails unless the inputs are doubles. Similarly it converts to matlab doubles for outputs (which would defeat the point of single-prec's smaller RAM footprint).

Here's my minimally complete example: This should be saved as `mwrapfloat.mw` :

```
% try float (single prec) arrays in mwrap. Length-1 for now. Barnett 7/5/20
%
% Compile with:
% mwrap -mex mwrapfloat -c mwrapfloat.cpp -mb mwrapfloat.mw
% mex mwrapfloat.cpp -largeArrayDims -output mwrapfloat

% then test in matlab:
% c = add(1,2); class(c)
% c = addf(1,2); class(c)             % currently gives 'double'
% c = addf(single(1),single(2));      % fails with "Invalid array argument"

$ void add(double *a, double *b, double *c) { *c = *a + *b; }
$ void addf(float *a, float *b, float *c) { *c = *a + *b; }

@function c=add(a,b)
# add(double[] a, double[] b, output double[1]c);

@function c=addf(a,b)
# addf(float[] a, float[] b, output float[1]c);
```

The commands are in the comments. Is there something I'm doing wrong?
If not, could you and Libin see if you can extend/patch mwrap to do the right thing here?
Thanks & best wishes, Alex

**Comment by zgimbutas** [comment]
Alex,

There is nothing wrong with your script. Mwrap has never included support
for single precision inputs, and everything would be converted to double on
the output. This convention goes back to the original David's code (mwrap
version 0.33). It also roughly corresponds to the convention used in
ancient Matlab. For FMM libraries, we always had to convert integers to
double precision as well (for flag processing). Since we never used single
precision in our codes, it was fine. The manual is somewhat imprecise, the
gateway interface describes the actual C/Fortran function calling sequence
- on the Matlab side, everything is currently double. In your case,

>> add(double(1/3),double(1/3))
ans =  0.666666666666667
>> addf(double(1/3),double(1/3))
ans =  0.666666686534882

so the code is executing correctly, using double precision in add, and
single precision in addf.

>> x = single(addf(double(single(1/3)),double(single(1/3))))
x =  0.666666686534882
>> class(x)
ans = single

is a temporary workaround to test your codes. Of course, this is terribly
inefficient, since it involves multiple conversions from/to single/double
precision, but at least it works.

It is possible to include proper single precision support by changing C
gateway code generation routines. Also, mwrap copiers will have to be
extended to handle single precision mxArrays. It is a bit tedious but
straightforward. I may need access to Matlab R2018a+ to test new complex
interleaved API.

Thanks for filing this, we should fix this since single precision is
becoming important for a lot of users.

Z

**Comment by ahbarnett** [comment]
Dear Zydrunas,
Well, that explains it! Since Matlab's probably not going away, and there is a growing user base of mwrap, adding correct float interfacing would be a super-useful feature ...for FMM's too.
I will ask Libin if he can set aside some time to help you on this.
Cheers,  Alex

**Comment by zgimbutas** [comment]
I pushed a working version supporting single precision Matlab arrays to
mwrap/single branch.

It is working quite well under octave, but I need Matlab testers (I have a
very limited access to Matlab from home).

**Comment by ahbarnett** [comment]
Hi Zydrunas,
It nearly works! Meaning,
1) it does the right thing for floats.
2) if you send in doubles to a float interface it doesn't throw a matlab error (like should), just does incorrect. Likewise vice versa. 
3) matlab segfaults upon quit. - may be related to 2.

To run tests:
git clone https://github.com/ahbarnett/mwrapdemo.git
cd mwrapdemo
cp make.inc.mexgcc7 make.inc
edit make.inc so MWRAP points to your 0.33.11
cd singleprec
make
open matlab, run 'test'

With R2017a, and mex using gcc-7.5.0 on ubuntu 16.04 LTS, I get:
```
>> test
c =
         0.666666666666667
ans =
    'double'
c =
     1.03889377298946e-314
c =
  single
    2.932031e+13
ans =
    'single'
c =
  single
       0.6666667
>> quit
*** Error in `/usr/local/MATLAB/R2017a/bin/glnxa64/MATLAB': double free or corruption (out): 0x00007fb660b34c20 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fb68b5cd7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7fb68b5d637a]
etc...
```
So, it's close...    Thanks,  Alex

**Comment by ahbarnett** [comment]
octave 4.2.2 on same sys:

octave:2> test
c =    0.666666666666667
ans = double
c = 1.64891879163447e-301
c =       29320309374976
ans = single
c =    0.666666686534882

so, either copying or throwing error (was the old style, preferred, don't you think) would be needed for the middle two cases.
Cheers, Alex

**Comment by zgimbutas** [comment]
Thanks, Alex, I see that there is a double deallocation bug while using float input arrays. It is fixed now:

>> test
c =
         0.666666666666667
ans =
double
c =
     1.03889377298946e-314
c =
    2.932031e+13
ans =
single
c =
       0.6666667
>> quit
$ 

What would be the best strategy to handle type conversion between single and double for cases #2 and #3? Right now, mwrap does no checking at all.

**Comment by lu1and10** [comment]
Hi Zydrunas,

Thanks for the quick fix, I did not even look at the code yet.
I will take a look at the code and be more familiar with it so later I can
help to maintain. Thanks!

Best,
Libin

**Comment by ahbarnett** [comment]
Ok, I tested the new 0.33.11 - same answers, no crash upon quit :)

Re cases 2,3 (wrong input data), I think the safest is to catch an error. It turns out the old code 0.33.3 does this, but only sometimes (I don't know when exactly).
That's what made me think it always checks, but, no, you're right, it doesn't. Here's 0.33.3 on two of the test cmds:
```
>> c = addf(single(1)/3,single(1)/3)
Error using mwrapfloat
Invalid array argument
Error in addf (line 3)
[c] = mwrapfloat(mex_id_, a, b, 1); 
>> c = add(single(1)/3,single(1)/3) 
c =
     1.03889377298946e-314
```
Weirdly, it only returns the "not-double" error when compiled on a single.
Here's the generated code segment in ` mxWrapGetArrayDef` :
```
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS) { \
        *e = "Invalid array argument"; \
        return 0; \
    } \
```
It must check on the fly the class of matlab object passed in (and has it backwards: it raises error on float, ok w/ double).

So, for the new version the best would be it raises similar type of error, but only in the appropriate cases.  I don't think it should make a copy at all, nor should it just operate on the wrong data type as it does now (could segfault).   (I guess for complex it still makes a copy, not sure the latest on that case?)
Cheers, Alex

**Comment by zgimbutas** [comment]
Yes, I noticed that too. The error used to be caught only for inout arrays. I added error catching logic for inputs, both float/double arrays and their complex versions.

I am now checking if arguments are mismatched before the final function is called, and will jump to the memory cleanup label, if an error is detected.

I pushed the changes to the repository, please give it a try.  The code also needs to be stressed for -R2018 flag, and for both C and C++ compilers.

**Comment by ahbarnett** [comment]
Works great:
```
>> test
c =
         0.666666666666667
ans =
    'double'
ans =
    'Invalid array argument, mxDOUBLE_CLASS expected'
good
ans =
    'Invalid array argument, mxSINGLE_CLASS expected'
good
c =
  single
       0.6666667
```

I also have been "stress-testing" in the gi_v2_dualmat branch of FINUFFT - thanks for being so fast!

It's working well. I have a problem w/ type 3 giving wrong numbers, others are good, so probably my fault.

We should make a decision on non-array mwrap arguments. At the moment they seem to behave as follows: the interfaces work for double and float, but non-double matlab-side input raises a "Invalid scalar argument" error.  Ie, you have to send in double even when you define a scalar float interface.
Presumably it copies to a float and passes that?
Do you agree it would be more logical to duplicate the style you had for arrays? No right answer here; an interface for "dummies" would always copy, even if it risks losing precision; one for "experts" would always raise an error.

Best, Alex

**Comment by zgimbutas** [comment]
I fixed scalar type checking in mwrap. This is relevant only for C/C++
codes, since Fortran passes arguments by reference only. So obviously, I
never checked it!

Testing was performed with octave using C++
```
        $(MWRAP) -cppcomplex  -mex mwrapfloat -c mwrapfloat.cpp -mb
mwrapfloat.mw
        mkoctfile --mex  mwrapfloat.cpp -output mwrapfloat
```
I also checked complex scalars:
```
% try float (single prec) arrays in mwrap. Length-1 for now. Barnett, G-
7/7/20
%
% Compile with:
% mwrap -mex mwrapfloat -c mwrapfloat.cpp -mb mwrapfloat.mw
% mex mwrapfloat.cpp -largeArrayDims -output mwrapfloat

% then test in matlab:
% c = add(1,2); class(c)
% c = addf(1,2); class(c)             % currently gives 'double'
% c = addf(single(1),single(2));      % fails with "Invalid array argument"

$#include <complex>

$typedef std::complex<double> dcomplex;
$#define real_dcomplex(z) std::real(z)
$#define imag_dcomplex(z) std::imag(z)
$#define setz_dcomplex(z,r,i)  *z = dcomplex(r,i)

$typedef std::complex<float> fcomplex;
$#define real_fcomplex(z) std::real(z)
$#define imag_fcomplex(z) std::imag(z)
$#define setz_fcomplex(z,r,i)  *z = fcomplex(r,i)

$ void add(double a, double b, double *c) { *c = a + b; }
$ void addf(float a, float b, float *c) { *c = a + b; }

$ void cadd(dcomplex a, dcomplex b, dcomplex *c) { *c = a + b; }
$ void caddf(fcomplex a, fcomplex b, fcomplex *c) { *c = a + b; }

@function c=add(a,b)
# add(double a, double b, output double[1]c);

@function c=addf(a,b)
# addf(float a, float b, output float[1]c);

@function c=cadd(a,b)
# cadd(dcomplex a, dcomplex b, output dcomplex[1]c);

@function c=caddf(a,b)
# caddf(fcomplex a, fcomplex b, output fcomplex[1]c);
```

Please give it a try. For consistency, I catch all errors and do not
convert automatically.

Best, Zydrunas

**Comment by ahbarnett** [comment]
Hi Zydrunas,
Thanks for doing this - the end result is going to be more professional than mwrap's ever been! There's one case to iron out: correct dcomplex array inputs report
'Invalid array argument, mxSINGLE_CLASS expected'.

(This breaks mwrap on the finufft master branch).

Maybe it's to do with -cppcomplex, which is what I use as an mwrap flag.
In fact without this flag mwrap fails (whether I include or remove your setz_* defs) with:
Error (58): c cannot be an array of object dcomplex
etc.

On this topic I don't see your need for setz_* etc, since -cppcomplex provides these.
I checked none of this affects the type error.

You can duplicate by running my latest round of tests:
https://github.com/ahbarnett/mwrapdemo/tree/master/singleprec
As usual:
make
in matlab: test

tail is:
```
array complex routines...
ans =
    'Invalid array argument, mxSINGLE_CLASS expected'
****** bad
ans =
    'Invalid array argument, mxDOUBLE_CLASS expected'
good
ans =
    'Invalid array argument, mxSINGLE_CLASS expected'
good
c =
  3×1 single column vector
     0.6666667 +     1.333333i
     0.6666667 +     1.333333i
     0.6666667 +     1.333333i
```

We should bring these tests into mwrap repo, along with mwrapdemo, now we're in charge.

Meanwhile I still get wrong answers for type-3 so I'll try various reverts...   Best, Alex

**Comment by ahbarnett** [comment]
by the way, the complex numbers passed in single-prec are correct - I fixed my type-3 bug! :)

**Comment by zgimbutas** [comment]
Thanks, Alex, for testing it!   There is indeed a dcomplex processing bug
that I introduced while trying to fix and tidy other parts of mwrap. It is
corrected now.

As for confusion with -cpp complex flag, support for fcomplex and dcomplex
was included too late, after the user-defined C/C++ code. Since it is so
confusing, I rearranged mwrap generated code so that fcomplex and dcomplex
are defined early on. The following code should compile properly:

```
% try float (single prec) arrays in mwrap. Length-1 for now.
% Barnett & Gimbutas 7/5/20-7/8/20
%
% Compile with:
% mwrap -mex mwrapfloat -c mwrapfloat.cpp -mb mwrapfloat.mw -cppcomplex
% mex mwrapfloat.cpp -largeArrayDims -output mwrapfloat

% then test in matlab with test.m
% *** need pass-fail


% REAL======================================================

% scalar real.........

$ void add(double a, double b, double *c) { *c = a + b; }
@function c=add(a,b)
# add(double a, double b, output double[1]c);

$ void addf(float a, float b, float *c) { *c = a + b; }
@function c=addf(a,b)
# addf(float a, float b, output float[1]c);

% array real........

$ void arradd(double *a, double *b, double *c, int n)
$ { for (int i=0;i<n;++i) c[i] = a[i] + b[i]; }
@function c=arradd(a,b)
n = numel(a);
# arradd(double[n] a, double[n] b, output double[n]c, int n);

$ void arraddf(float *a, float *b, float *c, int n)
$ { for (int i=0;i<n;++i) c[i] = a[i] + b[i]; }
@function c=arraddf(a,b)
n = numel(a);
# arraddf(float[n] a, float[n] b, output float[n]c, int n);


% COMPLEX=========================================================

% scalar complex.........

$ void addz(dcomplex a, dcomplex b, dcomplex *c) { *c = a + b; }
@function c=addz(a,b)
# addz(dcomplex a, dcomplex b, output dcomplex[1]c);

$ void addc(fcomplex a, fcomplex b, fcomplex *c) { *c = a + b; }
@function c=addc(a,b)
# addc(fcomplex a, fcomplex b, output fcomplex[1]c);

% array complex ........

$ void arraddz(dcomplex *a, dcomplex *b, dcomplex *c, int n)
$ { for (int i=0;i<n;++i) c[i] = a[i] + b[i]; }
@function c=arraddz(a,b)
n = numel(a);
# arraddz(dcomplex[n] a, dcomplex[n] b, output dcomplex[n]c, int n);

$ void arraddc(fcomplex *a, fcomplex *b, fcomplex *c, int n)
$ { for (int i=0;i<n;++i) c[i] = a[i] + b[i]; }
@function c=arraddc(a,b)
n = numel(a);
# arraddc(fcomplex[n] a, fcomplex[n] b, output fcomplex[n]c, int n);
```

The output is

```
$ octave test.m
warning: function ./test.m shadows a core library function
scalar real routines...
c =    0.666666666666667
ans = double
ans = mwrapfloat: Invalid scalar argument, mxDOUBLE_CLASS expected
good
ans = mwrapfloat: Invalid scalar argument, mxSINGLE_CLASS expected
good
c =    0.666666686534882

array real routines...
c =
     0.666666666666667
     0.666666666666667
     0.666666666666667
ans = double
ans = mwrapfloat: Invalid array argument, mxDOUBLE_CLASS expected
good
ans = mwrapfloat: Invalid array argument, mxSINGLE_CLASS expected
good
c =
     0.666666686534882
     0.666666686534882
     0.666666686534882

scalar complex routines...
c =    0.666666666666667 +     1.33333333333333i
ans = double
ans = mwrapfloat: Invalid scalar argument, mxDOUBLE_CLASS expected
good
ans = mwrapfloat: Invalid scalar argument, mxSINGLE_CLASS expected
good
c =    0.666666686534882 +     1.33333337306976i

array complex routines...
c =
     0.666666666666667 +     1.33333333333333i
     0.666666666666667 +     1.33333333333333i
     0.666666666666667 +     1.33333333333333i
ans = double
ans = mwrapfloat: Invalid array argument, mxDOUBLE_CLASS expected
good
ans = mwrapfloat: Invalid array argument, mxSINGLE_CLASS expected
good
c =
     0.666666686534882 +     1.33333337306976i
     0.666666686534882 +     1.33333337306976i
     0.666666686534882 +     1.33333337306976i
```

Everything checks out,

Best, Zydrunas

**Comment by zgimbutas** [comment]
Great, type-3 codes are tricky!

**Comment by ahbarnett** [comment]
Excellent! Works my end too! What do you think about including such self-tests and demos in the mwrap repo?

**Comment by zgimbutas** [comment]
Yes, that is a good idea.

**Comment by zgimbutas** [comment]
I pushed single precision tests to mwrap single branch. 

By the way, test_transfers.mw was objecting to double to single precision conversion, as it should. The users will have to specify this type conversion manually from now on.

The only thing that has no been tested is -R2018a flag (I don’t have access to Flatiron cluster anymore), I will need help here.   Once this flag is properly tested, I will merge this branch into master.

**Comment by zgimbutas** [comment]
The code compiles with modern Matlab R2018a+,  merged single branch into master.
